const ERROR = 'error';
const INFO = 'info';
const WARNING = 'warning';
const dict = {
    // _general_message: the code range [0 - 999]
    0: ["You cannot edit code for this type of data input.", INFO],
    1: ["Select one or more validation categories.", INFO],
    2: ['Are you sure you want to delete this mapping?', INFO],
    3: ["Are you sure you want to delete {{args[0]}}?", INFO],
    4: ["Are you sure you want to delete the {{args[0]}} input?", INFO],
    6: ['To add the Python code for your data input, click <b>Add Now</b>.<br>To skip this step for now, click <b>Add Later</b>.', INFO],
    7: ['This action may override the saved configuration for the {{ args[0] }} source type. Do you want to continue?', INFO],
    9: ["Are you sure you want to delete the {{args[0]}} source type?", INFO],
    11: ["Are you sure you want to delete the {{args[0]}} field?", INFO],
    12: ["{{args[0].groupNum}} groups have been parsed.<br>The settings for {{args[0].changedGroupNum}} groups have been modified.<br>{{args[0].disabledGroupNum}} groups have been disabled.<br>There are {{args[0].eventNum}} events in total and {{args[0].eventCoverage}}% of them are covered by the enabled regular expressions.", INFO],
    13: ["<b>{{args[0]}}</b> was uploaded successfully.", INFO],
    14: ["Please wait. This action may take some time.", INFO],
    16: ["You can use the Add-on Builder to map Data models, create alert actions, do field extractions, and validate and package <b>{{args[0]}}</b>. However, you can't use other features because this add-on was not created by the Add-on Builder.", INFO],
    19: ["The {{args[0]}} add-on could not be upgraded.", ERROR],
    20: ["The Splunk KVStore service is not available. For detailed information, run a search on 'index=_internal source=*web_service.log'.", ERROR],
    27: ["Are you sure you want to delete the {{args[0]}} alert action?", INFO],
    28: ["Are you sure you want to leave the wizard? You will lose any configuration settings you have defined so far.", INFO],
    29: ["Your settings have been saved. Click Return to Validation to go back to the add-on validation process.", INFO],

    30: ["Congratulations, your add-on is ready to submit to Splunk App Certification.", INFO],
    31: ["Your add-on is not ready for Splunk App Certification. Fix the app certification errors in the validation results and try again.", INFO],
    32: ["Ready for certification", INFO],
    33: ["Not ready for certification", INFO],
    34: ["The {{args[0].app}} add-on project could not be exported because a problem occurred while saving the meta data.", ERROR],
    35: ["The {{args[0].app}} add-on project could not be imported because a problem occurred while loading the meta data.", ERROR],
    36: ["The '{{args[0].app}}' add-on project could not be imported because an add-on with this name already exists.", ERROR],
    37: ["The '{{args[0].app}}' add-on project could not be imported because an add-on with this name already exists.", ERROR],
    38: ["The root directory name in the package is not consistent with the add-on name.", ERROR],
    39: ["Splunk Enterprise could not load the add-on. The HTTP status code for this issue is {{args[0].http_code}}", ERROR],
    40: ["The add-on project could not be loaded because of an error with the meta data store.", ERROR],
    41: ["The {{args[0].app}} add-on project could not be loaded because of an error with the meta data store.", ERROR],
    42: ["Add-on project package file not found in the request.", ERROR],
    43: ["An error occurred while exporting the {{args[0].app}} add-on project. For detailed information, run a search on 'index=_internal source=*web_service.log'.", ERROR],
    44: ["Welcome to Splunk Add-on Builder. The list below displays the add-ons that are installed on this instance of Splunk Enterprise.", INFO],
    45: ["Splunk Enterprise could not load the {{args[0].app}} add-on. The HTTP status code for this issue is {{args[0].http_code}}", ERROR],

    46: ["{{args[0].app}} is a system app and cannot be deleted.", ERROR],
    47: ["{{args[0].app}} was not created using Splunk Add-on Builder and cannot be deleted.", ERROR],

    48: ["Splunk Enterprise could not delete the {{args[0].app}} add-on. The HTTP status code for this issue is {{args[0].http_code}}", ERROR],
    49: ["Splunk Enterprise fails to delete the {{args[0].app}} add-on.", ERROR],

    50: ["Are you sure you want to delete the selected add-ons?", INFO],
    51: ["Your tags will be overwritten if you save your new models.", INFO],
    53: ["Are you sure you want to delete this event type? Note that any associated knowledge objects will not be deleted.", INFO],
    55: ["No models selected", INFO],
    56: ["No source type is included in this event type.", INFO],
    60: ["The {{args[0].current_app}} add-on cannot be deleted. {{args[0].deleted_app_message}}", ERROR],
    62: ["The {{args[0].app}} add-on has been deleted.", INFO],
    63: ["The {{args[0].apps}} add-ons have been deleted.", INFO],
    64: ["The {{args[0].current_app}} add-on cannot be deleted because it was not created by Splunk Add-on Builder.", ERROR],

    70: ["The {{args[0].app_name}} add-on cannot be renamed. For detailed information, run the search: 'index=_internal source=*ta_builder.log'.", ERROR],
    71: ["This add-on cannot be renamed to {{args[0].new_name}} because the name is already used by the other add-on.", ERROR],
    72: ["Exporting Addon, it may take a while.....", INFO],
    73: ["No event is detected.", INFO],
    74: ["This action will remove stanza {{args[0].stanzaName}} from props.conf and add new stanza into current app's props.conf", INFO],

    75: ["The add-on project could not be imported because a problem occurred while extracting project file.", ERROR],
    76: ["The add-on project could not be imported because a problem occurred while extracting project file. The upload file is not a valid compressed file.", ERROR],
    77: ["Internal errors when importing add-on project. Please check the web_service.log to see the errors.", ERROR],
    78: ["Can not upgrade add-on. Please backup and remove directory {{args[0].dir}}, then try again.", ERROR],
    79: [
        "This add-on must be upgraded to support python 2 & 3. Along with this upgrade change, some other functionalities listed below may also be broken due to Enterprise breaking changes.<br/>" +
        "<ol>" + 
        "<li>Alert action panel no longer supports a checkbox as a configurable component. Previously used checkbox component would be replaced with a radio button group with yes/no options.</li>" + 
        "<li>If you have some customized code in modular inputs or modular alerts, please convert them to Python 2 & 3 compatible by yourself.</li>" +
        "<li>If you updated some Python files manually on file system directly, they will be reverted to Add-on Builder default ones. Please backup them in advance and port them to Python 2 & 3 compatible if you still want to use them.</li>" +
        "</ol>" + 
        "Please be noted that this action is irrevocable. By clicking Confirm button, program would start to run upgrade scripts against this add-on."
    , WARNING],
    80: ["This add-on needs an upgrade before it could be configured.", WARNING],
    // _general_error: the code range [1000 - 1999]
    1000: ["The REST call to {{ args[0].url }} failed.", ERROR],
    1001: ["The following errors occurred while uploading the sample data: {{args[0].err_msg}}", ERROR],
    1002: ["An error occurred while uploading the sample data.", ERROR],
    1003: ["An error occurred while deleting the {{args[0]}} add-on. For detailed information, run the search: 'index=_internal source=*web_service.log'.", ERROR],
    1004: ["An error occurred while saving current add-on information on the server. For detailed information, run the search: 'index=_internal source=*web_service.log'.", ERROR],
    1005: ["Required parameter is not set.", ERROR],
    // _basic_project_error: the code range [2000 - 2999]"
    2000: ["The add-on name cannot be blank.", INFO],
    2001: ["An error occurred while uploading {{ args[0] }}. {{ args[1] }}", ERROR],
    2002: ["An error occurred while creating {{ args[0].app_name }}: {{ args[0].reason }}", ERROR],
    2003: ["An error occurred while updating {{ args[0].app_name }}: {{ args[0].reason }}", ERROR],
    2004: ["An error occurred while renaming {{ args[0].app_name }}: {{ args[0].reason }}", ERROR],
    2013: ['You can only upload one image file.', INFO],
    2014: ['Multiple files are not allowed. Try again with one file selected.', INFO],
    2015: ["The add-on name cannot contain any of these characters: \< (less than), \> (greater than), \: (colon), \" (double quote), \/ (forward slash), \\ (backslash), \| (vertical bar or pipe), \? (question mark) and \* (asterisk).", INFO],
    2016: ['Icons are not found for a visible add-on.', INFO],
    2017: ['The add-on name cannot exceed 80 characters.', INFO],
    2018: ['This file is too large. The maximum allowed size is {{ args[1] }} MB, and this file is {{ args[0] }} MB.', INFO],
    2020: ["The add-on folder name can only contain alphanumeric characters, hyphens, and underscores.", INFO],
    2021: ["The add-on folder name suffix cannot be blank.", INFO],
    2022: ['The add-on name is not found.', ERROR],
    2023: ['The Add-on name in meta is not consistent with the name in url', ERROR],
    2024: ['The Add-on {{args[0].appname}} already exists in the Splunk apps directory.', ERROR],
    2025: ['The Add-on {{args[0].appname}} already exists in the meta store.', ERROR],
    2026: ['The Add-on directory {{args[0].dir}} is not found.', ERROR],
    2101: ["An error occurred while fetching the source type list from the server. For detailed information, run a search on 'index=_internal source=*web_service.log'.", ERROR],
    2102: ["An error occurred while deleting the source type list on the server. For detailed information, run a search on 'index=_internal source=*web_service.log'.", ERROR],
    // _configure_data_input_error: the code range [3000 - 3999]
    3000: ["The input name cannot be blank or contain a space.", INFO],
    3001: ["The source type cannot be blank.", INFO],
    3002: ["The time interval must be a number.", INFO],
    3003: ["The URL cannot be blank.", INFO],
    3004: ['The URL is not valid.', INFO],
    3005: ["The method cannot be blank.", INFO],
    3006: ["The header, parameter name, or value cannot be blank.", INFO],
    3007: ["The command cannot be blank.", INFO],
    3008: ["The variable name or value cannot be blank.", INFO],
    3009: ["An API method has not been selected.", INFO],
    3010: ["The {{ args[0].sourcetype }} source type already exists in the current add-on.", ERROR],
    3011: ["An input with the name {{ args[0].name }} already exists.", ERROR],
    3012: ["A source type with the name {{ args[0].sourcetype }} already exists in Splunk Enterprise.", ERROR],
    3013: ["Multiple options have the same name \"{{ args[0].name }}\".", INFO],
    3014: ["The modular input must have at least one variable.", INFO],
    3015: ["The input name cannot contain any of these characters: \< (less than), \> (greater than), \: (colon), \" (double quote), \/ (forward slash), \\ (backslash), \| (vertical bar or pipe), \? (question mark) and \* (asterisk).", INFO],
    3016: ["The input title cannot be blank.", INFO],
    3017: ["The source type name can only contain alphanumeric characters, underscores, hyphens, and colons.", INFO],
    3018: ["Global account components depend on this setting and will be removed from all of your data inputs in this add-on if you continue. Are you sure you want to uncheck this option?", INFO],
    3019: ["The account list is empty. Go to Add-on Setup Parameters to add one.", INFO],
    3020: ["Input mode is changed, so you need to change your Python code in your data input.", INFO],
    3021: ["Your JSON path can't match anything in the JSON", INFO],
    3022: ["It looks like you have been editing something. If you leave before saving, your changes will be lost.", INFO],

    3100: ["An error occurred while generating Python code for the {{ args[0].name }} input.", ERROR],
    3101: ["An error occurred while testing the data input.", ERROR],
    3102: ["The meta data for the data input is corrupted.", ERROR],
    3103: ["The {{ args[0].name }} input could not be created.", ERROR],
    3104: ["The {{ args[0].name }} input could not be updated.", ERROR],
    3105: ["The {{ args[0].name }} input could not be disabled because its meta data is corrupted.", ERROR],
    3106: ["The {{ args[0].name }} input has already been disabled.", INFO],
    3107: ["The {{ args[0].name }} input could not be disabled because it could not be found.", INFO],
    3108: ["The {{ args[0].name }} input could not be enabled because its meta data is corrupted.", ERROR],
    3109: ["The {{ args[0].name }} input is already enabled.", INFO],
    3110: ["The {{ args[0].name }} input could not be enabled because it could not be found.", INFO],
    3113: ["The {{ args[0].name }} input could not be disabled because of this server error: '{{ args[0].message }}'.", ERROR],
    3114: ["The {{ args[0].name }} input could not be enabled because of this server error: '{{ args[0].message }}'.", ERROR],
    3115: ["The data input was not found in the input collection because the meta data is corrupted.", ERROR],

    3116: ["The {{ args[0].name }} input could not be created. Specify a source type and try again.", ERROR],
    3117: ["The {{ args[0].name }} input could not be created because the '{{ args[0].sourcetype }}' source type could not be created: '{{ args[0].msg }}'.", ERROR],
    3118: ["The {{ args[0].name }} input could not be created because the add-on root directory was not found.", ERROR],
    3119: ["The {{ args[0].name }} input already exists.", ERROR],

    3120: ["An error occurred while saving the code for the data input.", ERROR],
    3121: ["An error occurred while fetching the code for the data input.", ERROR],

    3122: ["The Add-on Builder could not be loaded because the current user `{{ args[0].user }}` does not have admin privileges.", ERROR],
    3123: ["The Add-on Builder could not be loaded because the current server is in a search head cluster.", ERROR],

    3125: ["There are multiple header variables named \"{{ args[0].name }}\" in the REST API configuration.", INFO],
    3126: ["There are multiple parameter variables named \"{{ args[0].name }}\" in the REST API configuration.", INFO],
    3127: ["There are multiple variables named \"{{ args[0].name }}\" in the setup page configuration.", INFO],
    3128: ["The global setting configuration could not be saved to the server.", ERROR],

    3129: ["The code for the {{args[0].input_name}} input could not be retrieved.", ERROR],
    3130: ["Variable data is corrupted.", INFO],
    3131: ["The name '{{args[0].prop_name}}' is not valid. Variable names should start with an alphabetic character, followed by alphanumeric characters or underscores.", INFO],
    3132: ["Input parameter name '{{args[0].prop_name}}' is a reserved keyword.", ERROR],
    3133: ["Input names should start with an alphabetic character, followed by alphabetic characters or underscores. The name must match the regex '[a-zA-Z]\\w*'", INFO],

    3134: ["The name '{{ args[0] }}' is not valid. The name should start with an alphanumeric character, followed by alphanumeric characters, underscores, or hyphens. The name must match the regex '^[a-zA-Z][0-9a-zA-Z_]*$'", INFO],

    3135: ["The Add-on Builder could not be loaded because the current server is in an indexer cluster.", ERROR],

    3136: ["The input name '{{args[0].input_name}}' conflicts with an existing Python module name.", ERROR],
    3137: ["The property name {{args[0].property_name}} cannot be empty.", ERROR],
    3138: ["An error occurred while validating the settings for the data input.", ERROR],
    3139: ["The test job ID was not found when checking the testing job.", ERROR],
    3140: ["The test job ID was not found when ending the testing job.", ERROR],

    3141: ["Python code was not found for the '{{args[0].input_name}}' input.", ERROR],
    3142: ["The test job ID was not found when testing the '{{args[0].input_name}}' input.", ERROR],
    3143: ["The input name '{{args[0].input_name}}' conflicts with an existing alert action name.", ERROR],
    3144: ["'{{args[0].attribute}}' is required in customized variable setting.", ERROR],
    3145: ["'{{args[0].input_name}}' is a reserved input name.", ERROR],

    3150: ["Code was not found when saving the data input.", ERROR],
    3151: ["Input type in meta is not 'rest' for the REST api data input.", ERROR], // Should this error message be removed?
    3152: ["The REST URL was not found.", ERROR],
    3153: ["The REST method was not found.", ERROR],
    3154: ["The REST URL value is not set.", ERROR],
    3155: ["The REST method value is not set.", ERROR],
    3156: ["The JSON object was not found for the specified JSON path.", ERROR],
    3157: ["The JSON path was not found for the JSON object.", ERROR],
    3158: ["Checkpointing is enabled, but the checkpoint parameter name cannot be found.", ERROR],
    3159: ["Checkpointing is enabled, but the checkpoint name is empty.", ERROR],
    3160: ["The checkpoint parameter name is already used by a data input parameter name.", ERROR],
    3161: ["Checkpointing variable names should start with an alphabetic character, followed by alphanumeric characters or underscores.", INFO],
    3162: ["The JSON path is invalid.", ERROR],
    3163: ["The inputs.conf file was not found in the local directory when disabling the {{args[0].name}} input. Your add-on is corrupted.", ERROR],
    3164: ["The inputs.conf file was not found in the local directory when enabling the {{args[0].name}} input. Your add-on is corrupted.", ERROR],
    3165: ["The JSON path is invalid.", ERROR],
    3166: ["Checkpointing variable name cannot be blank.", ERROR],
    3167: ["Checkpointing field path cannot be blank.", ERROR],
    3168: ["Checkpointing source timestamp format and target timestamp format should be set at the same time.", ERROR],
    3169: ["Source timestamp format is not set.", ERROR],
    3170: ["Target timestamp format is not set.", ERROR],
    3171: ["The input name cannot exceed {{args[0].length}} characters.", ERROR],
    3172: ["The input display name cannot exceed {{args[0].length}} characters.", ERROR],

    // _field_extract_error: the code range [4000 - 4999]
    4000: ["An error occurred while parsing or loading the field extraction results. For detailed information, run a search on 'index=_internal source=*web_service.log'.", ERROR],
    4001: [ "The field extraction results were not saved because an error occurred on the server. For detailed information, run a search on 'index=_internal source=*web_service.log'.", ERROR],
    4002: ["The regular expression is not valid.", INFO],
    4003: ["Groups cannot have the same name.", INFO],
    4004: ["Fields cannot have the same name.", INFO],
    4005: ["Field extractions for the {{ args[0].sourcetype }} source type could not be generated. Upload more sample files and try again.", ERROR],
    4006: ["Field extractions do not exist for the {{ args[0].sourcetype }} source type.", ERROR],
    4007: ["The field name must be a qualified Python identifier.", INFO],
    4008: ["The group name must be a qualified Python identifier.", INFO],
    4009: ["The Field Extractor does not fully support the {{ args[0].format }} format at this time, and parsing this file might not yield usable results. If you want to try anyway, click <b>Continue</b>.", INFO],
    4010: ["The regular expression has more than 100 capture groups. Split the long events to shorter ones and try again.", INFO],
    4011: ["There are no events indexed for the {{ args[0].sourcetype }} source type. Upload events and try again.", ERROR],
    4012: ["The {{ args[0].regex }} delimiter is not a valid regular expression.", ERROR],
    4013: ["The {{ args[0].regex }} regular expression for the Key Value data format should have only two capture groups.", ERROR],
    4014: ["Are you sure you want to delete the extraction results for the {{args[0]}} source type?", INFO],
    4015: ["An error occurred while previewing parsing results for the Unstructured data format. Events in this sample might be too complicated or too large to be parsed.", ERROR],
    4016: ["An error occurred while parsing results for the Unstructured data format. For detailed information, run a search on 'index=_internal source=*ta_builder.log'.", ERROR],
    4017: ["Some events contain non-ASCII characters. Remove these characters from your data, then try parsing again.", ERROR],

    4100: ["An error occurred while previewing parsing results for the Key Value data format. For detailed information, run a search on 'index=_internal source=*web_service.log'.", ERROR],
    4101: ["An error occurred while previewing parsing results for the Table data format. For detailed information, run a search on 'index=_internal source=*web_service.log'.", ERROR],
    4102: ["Cannot get contents of sourcetype {{args[0].sourcetype}}", ERROR],

    4200: ["The \"{{ args[0].field_name }}\" field has been renamed to \"{{ args[0].rename_field}}\" to follow Splunk field naming standards.", INFO],
    4201: ["The \"{{ args[0].field_name }}\" field was not extracted because it is a duplicate of a field that has already been extracted.", INFO],
    4202: ["The \"{{ args[0].field_name }}\" field has been renamed to None to follow Splunk field naming standards. This field was not extracted even if the delimiters or regex matched the sample.", INFO],
    4203: ["Please select the format you want to parse.", INFO],
    // _cim_mapping_error: the code range [5000 - 5999]
    5000: ["You have already mapped this field.", INFO],
    5001: ['The event field was not found in the EVAL expression.', INFO],
    5002: ["You must select at least one source type to continue configuring this event type.", INFO],
    5003: ["The {{args[0].src_field}} field could not be mapped as the {{args[0].dst_field}} field. {{args[0].err_msg}}", ERROR],
    5004: ["The {{args[0].src_field}} field could not be evaluated to the {{args[0].dst_field}} field. {{args[0].err_msg}}", ERROR],
    5005: ["The event type could not be created.", ERROR],
    5006: ["The {{ args[0].eventtype }} event type already exists in the current add-on.", ERROR],
    5007: ["The {{ args[0].eventtype }} event type already exists in Splunk Enterprise.", ERROR],
    5008: ["Event type names can only contain alphanumeric characters and underscores.", INFO],
    5009: ["The event type cannot be blank.", INFO],
    5010: ["Splunk Add-on Builder requires the Splunk Data Model add-on to be installed and enabled to perform Data Model mapping.", INFO],
    5011: ["An error occurred while verifying that the Splunk Common Information Model app is installed and enabled. For detailed information, run a search on 'index=_internal source=*web_service.log'.", ERROR],
    5012: ["The source type {{ args[0].sourcetype }} contains a wildcard in the search '{{ args[0].search }}'.", ERROR],
    5013: ["The search '{{ args[0].search }}' doesn't have explicit \"sourcetype=\" constraints for each search statement.", ERROR],
    5014: ["The source type {{ args[0].sourcetype }} from the search '{{ args[0].search }}' is not defined in the current app.", ERROR],
    5015: ["Brackets are mismatched in the string '{{ args[0].data }}'.", ERROR],
    5016: ["Quotes are mismatched in the string '{{ args[0].data }}'.", ERROR],
    5017: ["The EVAL function '{{ args[0].function }}' is invalid.", ERROR],
    5018: ["An EVAL with the field '{{ args[0].field }}' cannot be added because it was created by another EVAL in the {{ args[0].sourcetype}} source type."],
    5019: ["The fields '{{ args[0].fields }}' are not defined.", ERROR],
    5020: ["The EVAL for the '{{ args[0].field }}' field already exists.", ERROR],
    5021: ["The '{{ args[0].field }}' field cannot be used as a source field for FIELDALIAS because it is a target field for another FIELDALIAS/EVAL.", ERROR],
    5022: ["The model name '{{ args[0].name }}' could not be found in aob_models.conf.", ERROR],
    5023: ["The '{{ args[0].field }}' field cannot be aliased to itself.", ERROR],
    5024: ["A FIELDALIAS mapping for for the '{{ args[0].field }}' field already exists.", ERROR],
    5025: ["The {{ args[0].field }} source types are defined in search but not selected in the UI.", ERROR],
    5026: ["The {{ args[0].field }} source types are selected in the UI but not defnied in search.", ERROR],
    5027: ["'{{ args[0].search }}' is an invalid search.", ERROR],
    5028: [" A pipe character (|) is not allowed in an event type search.", ERROR],

    5030: ["Click to enter this field in the current 'Data Model Field' input box.", INFO],
    5031: ["Click to enter this field in the current 'Event Type Field or Expression' input box.", INFO],
    5052: ["The event type doesn't have related source type. Click <b>Add</b> to add one.", INFO],
    5054: ["You must reselect the model(s) you want to use. Your original tags have been preserved.", INFO],

    5060: ["Enter the field name before saving.", ERROR],
    5061: ["Field name \"{{ args[0].field }}\" contains whitespace(s). Please add double quotes to it.", ERROR],
    5062: ["Field name \"{{ args[0].field }}\" contains whitespace(s). Please add single quotes to it.", ERROR],
    5063: ["Doubel quote(s) in field name \"{{ args[0].field }}\" should be escaped.", ERROR],
    5064: ["Single quote(s) in field name \"{{ args[0].field }}\" should be escaped.", ERROR],

    5101: ["An error occurred while fetching the event type list from the server. For detailed information, run a search on 'index=_internal source=*web_service.log'.", ERROR],
    5102: ["An error occurred while creating the event type on the server. For detailed information, run a search on 'index=_internal source=*web_service.log'.", ERROR],
    5103: ["An error occurred while updating the event type on the server. For detailed information, run a search on 'index=_internal source=*web_service.log'.", ERROR],
    5104: ["An error occurred removing the event type on the server. For detailed information, run a search on 'index=_internal source=*web_service.log'.", ERROR],
    5105: ["An error occurred while fetching the fields and values of the event type from the server. For detailed information, run a search on 'index=_internal source=*web_service.log'.", ERROR],
    5106: ["An error occurred while fetching the knowledge objects of the event type from the server. For detailed information, run a search on 'index=_internal source=*web_service.log'.", ERROR],
    5107: ["An error occurred while creating the knowledge objects of the event type on the server. For detailed information, run a search on 'index=_internal source=*web_service.log'.", ERROR],
    5108: ["An error occurred while updating the knowledge objects of the event type on the server. For detailed information, run a search on 'index=_internal source=*web_service.log'.", ERROR],
    5109: ["An error occurred while removing the knowledge objects of the event type on the server. For detailed information, run a search on 'index=_internal source=*web_service.log'.", ERROR],
    5110: ["An error occurred while retrieving source type list of this application on the server. For detailed information, run a search on 'index=_internal source=*web_service.log'.", ERROR],

    5200: ["The 'default' folder of this add-on already contains the following configuration files: {{ args[0].names }}.", ERROR],
    5201: ["The 'default' folder of this add-on already contains the following configuration files: {{ args[0].names }}.<br>Continue to <b>Manage Source Types</b> will merge these files to the 'local' folder. If you want to package this add-on, go to <b>Validate & Package</b> and click <b>Download Package</b>.", INFO],
    5202: ["The 'default' folder of this add-on already contains the following configuration files: {{ args[0].names }}.<br>Continue to <b>Field Extraction</b> will merge these files to the 'local' folder. If you want to package this add-on, go to <b>Validate & Package</b> and click <b>Download Package</b>.", INFO],
    5203: ["The 'default' folder of this add-on already contains the following configuration files: {{ args[0].names }}.<br>Continue to <b>Map to Data Mode</b> will merge these files to the 'local' folder. If you want to package this add-on, go to <b>Validate & Package</b> and click <b>Download Package</b>.", INFO],


    5300: ["Please install at least one data model app", ERROR],
    5301: ["The data model scheme is not ready to load. For detailed information, run a search on 'index=_internal source=*addon-builder_ta_builder.log'. ", ERROR],
    5302: ["Cannot get the data models thru Splunk REST API. For detailed information, run a search on 'index=_internal source=*web_service.log'.", ERROR],
    5303: ["There is a parsing error for this app. For detailed information, run a search on 'index=_internal source=*addon-builder_ta_builder.log'. ", ERROR],
    // _validation_error: the code range [6000 - 6999]
    6000: ["The \"{{args[0].field}}\" field cannot be empty.", ERROR],
    6001: ["The \"{{args[0].field}}\" field must start with http:// or https://.", ERROR],
    6002: ["The \"{{args[0].field}}\" field cannot start with http:// or https://.", ERROR],
    6003: ["The \"Proxy Port\" field must be an integer between 1 - 65535.", ERROR],
    6004: ["The \"Proxy Type\" must be HTTP or HTTPS.", ERROR],
    6005: ["Login to the App Certification service failed. Verify your username and password and try again.", ERROR],
    6006: ["There was a problem connecting to the App Certification service. The service might not be available at this time, or you might need to verify your proxy settings and try again.", ERROR],
    6007: ["The \"Interval\" field must be an integer between 1 - 300", ERROR],
    6008: ["Your Splunk.com username and password are required for connecting to the App Certification service.", ERROR],
    6009: ["The value in the \"{{args[0].field}}\" field is invalid. Only alphanumeric characters, slashes (/), dashes (-), and periods (.) are allowed.", ERROR],
    6010: ["The \"timeout\" value must be an integer between 120 - 7200", ERROR],
    6011: ["The \"{{args[0]}}\" field cannot end with space.", INFO],
    6012: ["App precertification validation has not been performed.", INFO],
    6013: ["An error occurred while validating the app. For detailed information, run a search on 'index=_internal source=*validation_engine*'.", ERROR],
    // _summary_error: the code range [7000 - 7999]
    7000: ['Click to add new data inputs.', INFO],
    7001: ['Click to create alert actions.', INFO],
    7002: ['Click to download the add-on package.', INFO],

    // _sourcetype_error: the code range [8000 - 8999]
    8000: ["The {{args[0].sourcetype}} source type already exists in the current add-on.", ERROR],
    8001: ["An error occurred while updating the configuration for the {{args[0].sourcetype}} source type because it does not exist.", ERROR],
    8002: ["The {{args[0].sourcetype}} source type already exists in Splunk Enterprise.", ERROR],
    8003: ["The {{args[0].sourcetype}} source type could not be created.", ERROR],
    8004: ["The {{args[0].sourcetype}} source type could not be updated.", ERROR],
    8005: ["The source type name cannot be empty.", ERROR],
    8006: ["A duplicate \"{{ args[0].prop }}\" source type property was found.", INFO],
    8007: ["The property name cannot be empty.", INFO],
    8008: ["The property value cannot be empty.", INFO],
    8009: ["An error occurred while importing the {{ args[0].sourcetype }} source type.", ERROR],
    8010: ["An error occurred while retrieving source types.", ERROR],
    8011: ["A source type has not been selected.", INFO],
    8012: ["The name \"{{args[0].sourcetype}}\" is reserved by the Add-on Builder. Use a different source type name.", ERROR],
    8013: ["The archive file format is not supported.", INFO],
    8014: ["The binary file format is not supported.", INFO],
    8015: ["An error occurred while uploading sample data for the {{args[0].sourcetype}} source type.", ERROR],
    8016: ["The source type name \"{{args[0].sourcetype}}\" is not valid. Source type names should start with an alphabetic character, followed by alphanumeric characters, underscores, or colons.", ERROR],
    8017: ["This source type \"{{args[0].sourcetype}}\" exists in the add-on \"{{args[0].app}}\". If you want to import the source type to this add-on, click <b>Continue</b>. Be aware that the source type of the add-on \"{{args[0].app}}\" will be deleted and this is one-way operation.", INFO],
    // _utility_error: the code range [9000 - 9999]
    9000: ["The \"{{ args[0].filepath }}\" file or directory could not be created. Verify that you have the correct permissions to perform this action.", ERROR],
    9001: ["The \"{{ args[0].filepath }}\" file or directory could not be deleted. Verify that you have the correct permissions to perform this action.", ERROR],
    9002: ["The file could not be copied from \"{{ args[0].src_file }}\" to \"{{ args[0].dst_file }}\". Verify that you have the correct permissions to perform this action.", ERROR],
    9003: ["Contents could not be written to \"{{ args[0].filepath }}\". Verify that you have the correct permissions to perform this action.", ERROR],
    9004: ["The \"{{ args[0].filepath }}\" file could not be read. Verify that you have the correct permissions to perform this action.", ERROR],

    // _configure_modular_alert_error: the code range [10000 - 11000]
    10000: ["An alert action with the name {{ args[0].name }} already exists.", ERROR],
    10100: ["{{args[0]}} cannot be empty.", INFO],
    10101: ["{{args[0]}} text cannot exceed {{args[1]}} characters.", INFO],
    10102: ["{{args[0]}} can only contain alphanumeric characters and underscores.", INFO],
    10103: ["{{args[0]}} can only contain numeric characters and periods.", INFO],
    10104: ["{{args[0]}} already exists.", INFO],
    10105: ["{{args[0]}} should start with an alphabetic character, followed by alphanumeric characters or underscores.", INFO],
    10106: ["An alert action with the name {{args[0]}} already exists.", INFO],
    10107: ["{{args[0]}} should not contain uppercase letters.", INFO],
    10108: ["At least one option is required.", INFO],
    10109: ["{{args[0]}} can only contain alphanumeric characters, underscores, hyphens, and colons.", INFO],
    10110: ["Option definition should contain at least one label-value pair.", INFO],
    10111: ["The {{args[0].short_name}} alert action could not be saved.", ERROR],
    10112: ["Option values cannot be duplicated.", INFO],

    // global setting message: the code range is [11000 - 12000]
    11000: ["Add-on setup configuration is not valid. {{args[0].message}}", ERROR],
    11001: ["Global settings could not be saved. The required field '{{args[0].field}}' was not found in the definition of customized variable '{{args[0].v_name}}'.", ERROR], // Should this error message be removed?
    11005: ["Global settings could not be saved.", ERROR],
    11006: ["The setup parameter name '{{args[0].var_name}}' is a reserved keyword.", ERROR],
    11010: ["'{{args[0]}}' is a reserved input name.", INFO],
    11011: ["The input parameter name '{{args[0]}}' is a reserved keyword.", INFO],
    11012: ["The setup parameter name '{{args[0]}}' is a reserved keyword.", INFO],

    // _success page error: the code range [12000 - 13000]
    12000: ["Done!", INFO],
    12001: ["Add data inputs", INFO],
    12002: ["Extract fields", INFO],
    12003: ["Next steps", INFO],
    12004: ["Add alert actions", INFO],
    12005: ["Validate and package", INFO],
    // __unknown__ is reserved
    "__unknown__": ["An unknown error occurred.", ERROR],
    ERROR: ERROR,
    INFO: INFO,
    WARNING: WARNING,
};

export default dict;
